AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

# Stylistic preference to keep dev dependencies in gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

# Disabled on our repo's to enable polyglot-release
Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false
