before_install:
  gem install bundler -v 1.5.1
rvm:
  - 2.3.1
  - 2.4.0
  - ruby-head
script: make
matrix:
  include:
    - rvm: 1.9.3
      env: EXCLUDED_DIRS="activesupport-5.0.0"
    - rvm: 2.0.0
      env: EXCLUDED_DIRS="activesupport-5.0.0"
    - rvm: 2.1.3
      env: EXCLUDED_DIRS="activesupport-5.0.0"
    - rvm: 2.2.0
      env: EXCLUDED_DIRS="activesupport-5.0.0"
    - rvm: jruby
      env: EXCLUDED_DIRS="activesupport-5.0.0"
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
