#!/bin/bash

set -e

GEMFILE_FOLDER=$1
GEMFILE=$GEMFILE_FOLDER/Gemfile
SCENARIOS=$(cat $GEMFILE_FOLDER/scenarios)
PLATFORM="$(BUNDLE_GEMFILE=$GEMFILE bundle platform)"

echo

if [[ "$PLATFORM" =~ "Your Ruby version is" ]]; then
    echo "$PLATFORM: Skipping"
    exit 0
fi

for SCENARIO in $SCENARIOS; do
    SCENARIO_PATH=test/$SCENARIO
    BUNDLE_GEMFILE=$GEMFILE bundle install --quiet
    OUTPUT=$(BUNDLE_GEMFILE=$GEMFILE bundle exec ruby -I lib "$SCENARIO_PATH")
    if [[ -n "$OUTPUT" ]] && ! echo "$OUTPUT" | grep -q "0 runs, 0 assertions, 0 failures, 0 errors"; then
        echo "$GEMFILE_FOLDER -> Scenario: $SCENARIO - FAIL"
        echo "Expected output to be empty, but was:"
        echo "$OUTPUT"
        exit 1
    fi
    echo "$GEMFILE_FOLDER -> Scenario: $SCENARIO - PASS"
done
