# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport', '~> 8.0'
# TODO: The below restriction is required to stop an error from occurring. Needs investigation
gem 'minitest', '~> 5.0'
