name: Run ruby tests

inputs:
  ruby-version:
    description: Version of ruby to use with ruby/setup-ruby@v1
    required: false
    default: "3.0"

runs:
  using: "composite"

  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false
        cache-version: 1

    - name: Install gems
      run: bundle install
      env:
        BUNDLE_GEMFILE: test/gemfiles/${{ matrix.gemfile }}/Gemfile
      shell: bash

    - name: Run test scenario ${{ matrix.scenario }}
      run: |
        bundle exec ruby -I lib test/scenarios/${{ matrix.scenario }} > output.log
        if [[ -s output.log ]]; then
          echo "Expected no output but got:"
          cat output.log
          exit 1
        end
      env:
        BUNDLE_GEMFILE: test/gemfiles/${{ matrix.gemfile }}/Gemfile
      shell: bash
