name: Test

permissions: {}

on:
  push:
    branches:
      - main
      - renovate
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4', '4.0']
        gemfile: # These are duplicated from the test/gemfiles folder
          - activesupport-5
          - activesupport-6
          - activesupport-7
          - activesupport-8
          - minitest-5
          - minitest-6
          - plain-ruby
          - rspec-3
          - test-unit-3
        # Review this exclusion matrix as part of a v3 release. The goal is to remove the exclusions and
        # test all combinations of Ruby and gemfiles.
        exclude:
          # ActiveSupport
          # Unsupported versions of Ruby
          # :none_now
          # False failures to be Investigated
          - gemfile: activesupport-5
          - gemfile: activesupport-6
          - gemfile: activesupport-7
          - gemfile: activesupport-8
          # MiniTest
            # Unsupported versions of Ruby
          # :none_now
          # False failures to be Investigated
          - gemfile: minitest-5
          - gemfile: minitest-6

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - name: Run test scenarios
        run: ./test-gemfile test/gemfiles/${{ matrix.gemfile }}
        shell: bash
