name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ["2.6", "2.7", "3.0", "3.1"]
        gemfile: ["activesupport-4", "minitest-4"]
        scenario: []
        include:
          - gemfile: "activesupport-4"
          - scenario: "require_activesupport_testing_autorun.rb"
        include:
          - gemfile: "activesupport-4"
          - scenario: "minitest_assertions.rb"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Run ruby tests
        uses: ./.github/actions/test-ruby
        with:
          ruby-version: ${{ matrix.ruby }}
