name: Test

permissions: {}

on:
  push:
    branches:
      - main
      - renovate
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4', '4.0']
        gemfile:
          - activesupport-5
          - activesupport-6
          - activesupport-7
          - activesupport-8
          - minitest-5
          - minitest-6
          - plain-ruby
          - rspec-3
          - test-unit-3

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - name: Run test scenarios
        run: ./test-gemfile ./gemfiles/${{ matrix.gemfile }}
        shell: bash
